mutation CreateArrayDataset($input: CreateArrayDatasetInput!) {
  createArrayDataset(input: $input) {
    id
    name
  }
}

mutation RequestZarrUpload($input: RequestZarrUploadInput!) {
  requestZarrUpload(input: $input) {
    accessKey
    status
    secretKey
    bucket
    key
    sessionToken
    store
  }
}

mutation FinishZarrUpload($input: FinishZarrUploadInput!) {
  finishZarrUpload(input: $input) {
    id
    key
    bucket
    path
  }
}

mutation RequestZarrAccess($input: RequestZarrAccessInput!) {
  requestZarrAccess(input: $input) {
    accessKey
    secretKey
    bucket
    key
    sessionToken
    path
  }
}
